### PR TITLE
Add support for retain flag when publishing

### LINKED ISSUE #20: Support Retain for Publish
One useful pattern to track device up/down status is to have a will set to .../status with value '0' and retain, and when the device comes up to publish to the .../status with value '1' with retain. The retain allows the status to be interrogated at anytime by a client. The library has retain flag for will, but not for publish. Of course, it would be useful for lots of other things too, but thought I would point out one very valuable one...

### PR DESCRIPTION
**Pull request by ben-willmore**
This is an updated version of https://github.com/Fapiko/Adafruit_MQTT_Library/tree/retain-flag which uses function overloading instead of optional parameters, as suggested in #169. This would also resolve #20 and #161.

```
// Example usage
Adafruit_MQTT_Client mqtt(&client, MQTT_SERVER, MQTT_SERVERPORT, MQTT_USERNAME, MQTT_KEY);

Adafruit_MQTT_Publish feed1 = Adafruit_MQTT_Publish(&mqtt, "/feeds/feed1");
feed1.publish("retain", true); // retain
feed1.publish("discard", false); // don't retain
feed1.publish("discard"); // don't retain

Adafruit_MQTT_Publish feed2 = Adafruit_MQTT_Publish(&mqtt, "/feeds/feed2");
feed2.publish(1, true); // retain
feed2.publish(0, false); // don't retain
feed2.publish(0); // don't retain

Adafruit_MQTT_Publish feed3 = Adafruit_MQTT_Publish(&mqtt, "/feeds/feed3");
feed3.publish(1.0, true); // retain
feed3.publish(0.0, false); // don't retain
feed3.publish(0.0); // don't retain

mqtt.publish("/feeds/feed4", "retain", true); // retain
mqtt.publish("/feeds/feed4", "discard", false); // don't retain
mqtt.publish("/feeds/feed4", "discard"); // don't retain
```

### CODE REVIEW

**Comment by brentru** [comment]
@ben-willmore  Thank you for the PR. Are you interested in possibly adding an example, similar to the one you have above but within `examples/`, to serve as documentation for example usage?

**Comment by ben-willmore** [comment]
Sure, I will push an example when I get a chance (probably a couple of days).

**Review by brentru — APPROVED** [review]

**Comment by brentru** [comment]
@ben-willmore  Thank you for the Pull Request!

**Comment by ben-willmore** [comment]
@brentru Thank you too for working on it, I'm pleased to see this feature get merged.

**Pull request merged**
