### PR TITLE
Various fixes and improvements

### PR DESCRIPTION
**Pull request by matthijskooijman**
This pullrequest contains a number of fixes and small improvements I came across when working with this library. They are mostly minor changes and the commit messages should be self-explanatory.

### CODE REVIEW

**Comment by toddtreece** [comment]
FONA & ESP8266 examples confirmed working with Adafruit IO using this fork.

**Comment by toddtreece** [comment]
found my CC3k and ran the last example. everything works as expected.

@ladyada ok to merge?

**Comment by ladyada** [comment]
do it!

**Comment by matthijskooijman** [comment]
Thanks! :-D

**Pull request merged**
